ALTER TABLE `Discipline`
  ADD COLUMN `winPoints` INTEGER NOT NULL DEFAULT 3,
  ADD COLUMN `drawPoints` INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN `lossPoints` INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN `allowDraw` BOOLEAN NOT NULL DEFAULT true;
